version: '2'
services:
    backend:
        build: backend
        volumes:
            - ./backend:/usr/src/app
        ports:
            - 3030:3030
        links:
            - db
    db:
        image: mongo
    admin:
        build: admin
        volumes:
            - ./admin:/usr/src/app
        ports:
            - 3000:3000
            - 3001:3001
        links:
            - backend
